stocks_dbt:
  outputs:
    dev:
      dataset: stocks_refined_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: europe-west3
      method: service-account
      priority: interactive
      project: stocks-455113
      threads: 1
      type: bigquery
    prod:
      dataset: stocks_refined
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: europe-west3
      method: service-account
      priority: interactive
      project: stocks-455113
      threads: 1
      type: bigquery
  target: dev
